[package]
name = "schemius"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lazy_static = "1.4.0"
num = "0.4"
regex = "1"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
