[package]
name = "schemus-native"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
schemus = { path = "../schemus" }
