[workspace]

[package]
name = "schemius-web"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
schemius = { path = "../schemius" }
lazy_static = "1.4"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
