name: PAT test (dummy file regeneration)

on: workflow_dispatch

env:
  WASTE_DIR: ./.waste
  DUMMY_FILE: dummy.txt

jobs:
  regenerate-dummy-file:
    name: Regenerate dummy file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.ACTIONS_USER }}
          git config --global user.email ${{ secrets.ACTIONS_EMAIL }}

      - name: Add dummy file
        run: |
          mkdir -p $WASTE_DIR
          TARGET=$WASTE_DIR/$DUMMY_FILE
          DATE=$(date)
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "I am a dummy file! $DATE" > $TARGET
          git add $TARGET

      - name: Commit and push changes
        run: |
          git commit -m "Regenerate dummy file ($DATE)"
          git push
