name: PAT-TEST

on: workflow_dispatch

env:
  DUMMY_FILE: ./.github/workflows/dummy.txt

jobs:
  first-push:
    name: First push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.ACTIONS_USER }}
          git config --global user.email ${{ secrets.ACTIONS_EMAIL }}

      - name: Add dummy file
        run: |
          echo "I am a dummy file!" > $DUMMY_FILE
          git add $DUMMY_FILE

      - name: Commit and push changes
        run: |
          git commit -m "Add dummy file"
          git push

  second-push:
    name: Second push
    runs-on: ubuntu-latest
    needs: first-push
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name ${{ secrets.ACTIONS_USER }}
          git config --global user.email ${{ secrets.ACTIONS_EMAIL }}

      - name: Remove dummy file
        run: |
          git rm $DUMMY_FILE
          git add .

      - name: Commit and push changes
        run: |
          git commit -m "Remove dummy file"
          git push
